modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "hephaestus"
version = "${version}"
displayName = "Hephaestus"
authors = "tompinn23"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.hephaestus]]
    modId = "forge"
    mandatory = true
    versionRange = "[44,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hephaestus]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3,)"
    ordering = "NONE"
    side = "BOTH"