modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "euthenia"
version = "${version}"
displayName = "Euthenia"
authors = "tompinn23"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.euthenia]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.euthenia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"